services:
  web:
    build: .
    container_name: rag-web
    ports:
      - "60304:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rag_system
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - rag-network

  db:
    image: postgres:15
    container_name: rag-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rag_system
    volumes:
      - D:\docker_data\postgres:/var/lib/postgresql/data #windows
      #- ./data/postgres:/var/lib/postgresql/data  # linux
    restart: always
    networks:
      - rag-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  rag-network:
    name: rag-network
    driver: bridge 
